const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("bmrng", {
  devices: () => ipcRenderer.invoke("devices"),
  checkItunes: () => ipcRenderer.invoke("check-itunes"),
  announcement: () => ipcRenderer.invoke("announcement"),
  accountInfo: () => ipcRenderer.invoke("account-info"),
  accountLogin: (p) => ipcRenderer.invoke("account-login", p),
  accountLogout: () => ipcRenderer.invoke("account-logout"),
  catalog: () => ipcRenderer.invoke("catalog"),
  checkOwned: (app) => ipcRenderer.invoke("check-owned", app),
  install: (p) => ipcRenderer.invoke("install", p),
  onInstallProgress: (cb) => ipcRenderer.on("install-progress", (_e, m) => cb(m)),
  register: (b) => ipcRenderer.invoke("bmrng-register", b),
  verify: (b) => ipcRenderer.invoke("bmrng-verify", b),
  login: (b) => ipcRenderer.invoke("bmrng-login", b),
  me: () => ipcRenderer.invoke("bmrng-me"),
  consume: () => ipcRenderer.invoke("bmrng-consume"),
  topup: (b) => ipcRenderer.invoke("bmrng-topup", b),
  promoValidate: (b) => ipcRenderer.invoke("bmrng-promo", b),
  installLog: (b) => ipcRenderer.invoke("install-log", b),
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
  cancelInstall: () => ipcRenderer.invoke("cancel-install"),
  appVersion: () => ipcRenderer.invoke("app-version"),
  payConfig: () => ipcRenderer.invoke("pay-config"),
  checkUpdate: () => ipcRenderer.invoke("check-update"),
  applyUpdate: (info) => ipcRenderer.invoke("apply-update", info),
  onUpdateProgress: (cb) => ipcRenderer.on("update-progress", (_e, p) => cb(p)),
  configGet: () => ipcRenderer.invoke("config-get"),
  configSet: (p) => ipcRenderer.invoke("config-set", p),
});
